import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <h1>Carpe Diem</h1>
        <div>
          <p>로그인</p>
          <p>회원가입</p>
        </div>
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
